import type { GetStaticProps } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import { ArrowUpTrayIcon } from '@heroicons/react/24/solid'
import Link from 'next/link'
import { Experiences, PageInfo, Project, SkillSet, Social } from '../typings'
import { fetchPageInfo } from '../utils/fetchPageInfo'
import { fetchSocials } from '../utils/fetchSocials'
import { fetchExperience } from '../utils/fetchExperiences'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchProjects } from '../utils/fetchProjects'

type Props = {
  pageInfo: PageInfo,
  experiences: Experiences[],
  skills: SkillSet[],
  projects: Project[],
  socials: Social[],
}

const Home = ({ pageInfo, socials, experiences, skills, projects}: Props) => {
  return (
    <div className="bg-[#78350f] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-amber-800/20 scrollbar-thumb-amber-400/80">
      <Head>
        <title>Diana&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header socials={socials} />
      <section id="hero" className="snap-start">
        <Hero pageInfo={pageInfo} />
      </section>
      <section id="about" className="snap-center">
        <About pageInfo={pageInfo} />
      </section>
      <section id="experience" className="snap-center">
        <Experience experiences={ experiences} />
      </section>
      <section id="skills" className="snap-start">
        <Skills skills={skills} />
      </section>
      <section id="projects" className="snap-start">
        <Projects projects={projects} />
      </section>

      {/* Contact Me */}
      <section id="contact" className="snap-start">
        <Contact pageInfo={pageInfo} />
      </section>

      {/* Footer */}
      <Link href="#hero">
        <footer className="sticky bottom-5 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <ArrowUpTrayIcon className="h-10 w-10 rounded-full filter  grayscale hover:grayscale-0 cursor-pointer" />
          </div>
        </footer>
      </Link>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const socials: Social[] = await fetchSocials();
  const experiences: Experiences[] = await fetchExperience();
  const skills: SkillSet[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();

  return {
    props: {
      pageInfo,
      socials,
      experiences,
      skills,
      projects,
    },
  };
}
